### PR TITLE
fix: improve handling for YAML version directives

### LINKED ISSUE #998: Conftest fails on YAMLs with version
I wanted to check a YAML document with the YAML version in the preamble 

```yaml
%YAML 1.1
---
group_id: 1234
```

... using ...

```shell
conftest test --parser yaml test.yml
```

However, conftest fails stating 

```log
Error: running test: parse configurations: parser unmarshal: unmarshal multiple documents: unmarshal subdocument yaml: error converting YAML to JSON: yaml: line 1: did not find expected <document start>, path: test.yml
```

If I remove the preamble, it works.

### PR DESCRIPTION
**Pull request by thevilledev**
The YAML parser was incorrectly splitting documents with version directives (e.g. '%YAML 1.1') by treating the first '---' marker as a document separator. This caused the version directive to be separated from its document, resulting in parsing errors. Fixed document separation logic to keep version directive with its document.

Added test cases for various YAML scenarios and improved test coverage.

Fixes #998

### CODE REVIEW

File: parser/yaml/yaml.go [hunk 1]
```diff
@@ -29,12 +29,35 @@ func (yp *Parser) Unmarshal(p []byte, v interface{}) error {
 }
 
 func separateSubDocuments(data []byte) [][]byte {
+	// Determine line ending style
 	linebreak := "\n"
-	if bytes.Contains(data, []byte("\r\n---\r\n")) {
+	if bytes.Contains(data, []byte("\r\n")) {
 		linebreak = "\r\n"
 	}
+	separator := fmt.Sprintf("%s---%s", linebreak, linebreak)
```
Comment (anderseknert) [inline parser/yaml/yaml.go:37]: Since we're working with bytes here already, I'd probably just stick to that. 

```go
var (
	lf   = []byte{'\n'}
	crlf = []byte{'\r', '\n'}
	sep  = []byte{'-', '-', '-'}
)

func separateSubDocuments(data []byte) [][]byte {
	// Determine line ending style
	linebreak := lf
	if bytes.Contains(data, crlf) {
		linebreak = crlf
	}

	separator := slices.Concat(linebreak, sep, linebreak)

	// Count actual document separators
	parts := bytes.Split(data, separator)
```

But that's optional :)

**Review by anderseknert — APPROVED** [review]
Looks great to me! Left a small suggetion, but looks good to merge for me.

File: parser/yaml/yaml.go (hunk 1 above)
Comment (thevilledev) [reply parser/yaml/yaml.go:37]: Good idea! I'll do this
